In [62]:
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error ,  r2_score
import pandas as pd 
import pickle



df =  pd.read_csv("data_dropna.csv")
print(df)
drop_list = ['Unnamed: 0.1', 'Unnamed: 0','Room' ]
df = df.drop(columns=drop_list)
print(df)
df = df[['Main_floor','Idex_name', 'Price']]

print(df)




X = df.iloc[:, :-1]
print(X)
y = df.iloc[:, -1] 


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train = X_train.to_numpy()
X_test = X_test.to_numpy()
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()




scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)




lasso_model = Lasso(alpha=0.01)  


lasso_model.fit(X_train_scaled, y_train)


y_pred = lasso_model.predict(X_test)


mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
r2 = r2_score(y_test, y_pred)
print(r2,'r2')

print("Model Coefficients:")
for feature, coefficient in zip(range(1, X.shape[1]+1), lasso_model.coef_):
    print(f"Feature {feature}: {coefficient}")
    
with open('lasso_model_new_2.pkl', 'wb') as model_file:
    pickle.dump(lasso_model, model_file)


      Unnamed: 0.1  Unnamed: 0  Room  Idex_name     Price    s  max_floor  \
0               96          96     4          0  135000.0  107         14   
1               97          97     3          0  150000.0   74          9   
2               98          98     2          0   95000.0   40          9   
3               99          99     3          0   99000.0   70         16   
4              100         100     3          0  174000.0   98          9   
...            ...         ...   ...        ...       ...  ...        ...   
4468          4699        4699     3         10  130000.0   87         14   
4469          4700        4700     3         10  122000.0   97          9   
4470          4701        4701     4         10  170000.0   96         10   
4471          4702        4702     3         10   86000.0   74          9   
4472          4703        4703     2         10   75000.0   50          4   

      Main_floor  
0           13.0  
1            2.0  
2            2.0  

In [28]:
X_test_scaled

array([[ 0.09231386, -1.37381492,  0.36665225,  0.37187313, -0.81510969],
       [-0.27219494,  0.92460621,  0.36665225,  0.2835877 ,  1.15192945],
       [-0.27219494, -0.79920964, -0.79319797, -0.20198215,  1.15192945],
       ...,
       [ 2.27936668,  0.35000093,  1.52650246,  1.34301284,  0.49624973],
       [-0.27219494, -0.22460436,  0.36665225,  0.01873142, -1.4707894 ],
       [ 0.82133147,  1.4992115 ,  0.36665225,  1.16644198,  0.49624973]])

In [61]:
import numpy as np
# Max_floor  Main_floor  Room   S  Idex_name
arr = np.array([5,0])
arr = arr.reshape(1,-1)
print(arr)
lasso_model.predict(arr)

[[5 0]]


array([118095.9874438])

In [49]:
with open("C:\\Users\\haykz\\OneDrive\\Desktop\\StartUp\\StartUp\\lasso_model_new_2.pkl", 'rb') as model_file:
    predict_price = pickle.load(model_file)
    price = predict_price.predict(arr)
    print(price)


[928835.11194269]
